# Generated by Django 3.2.8 on 2021-10-16 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': ()},
        ),
    ]
