# Generated by Django 3.2.8 on 2021-10-30 08:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=15)),
                ('birthday', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('genere', models.CharField(choices=[('FI', 'Fiction'), ('NO', 'Novel'), ('PO', 'Poetry'), ('FA', 'Fantasy')], max_length=2)),
                ('date_writed', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('score', models.IntegerField(default=0, verbose_name='score')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='details.author')),
            ],
        ),
    ]
