# Generated by Django 3.2.8 on 2021-10-16 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_uc_books', 'Can update or create books'),)},
        ),
    ]
