# Generated by Django 3.2.8 on 2021-10-16 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
    ]
